#!/usr/bin/env python3

import argparse
import sys
from crawler import Crawler

# define if the arguments are valid
def validate(args):
    if len(args) != 3:
        raise SyntaxError('Correct syntax is \'[username] [password]\'')
    else:
        return True

if __name__ == '__main__':
    if validate(sys.argv):
        parser = argparse.ArgumentParser()
        parser.add_argument('name')
        parser.add_argument('username')
        parser.add_argument('password')
        args = parser.parse_args(sys.argv)
        crawler = Crawler()
        crawler.run(args.username, args.password)